syntax enable
:color peachpuff
set nocp
set wildmenu
set relativenumber
set ignorecase
set smartcase
set incsearch
set nowrap
set tabstop=4
set softtabstop=0
set expandtab
set shiftwidth=4
set showcmd
set clipboard=unnamed
set laststatus=2
set clipboard+=unnamedplus
set ru
