syntax enable
:color peachpuff
set nocp
set wildmenu
set number
set ignorecase
set smartcase
set incsearch
"set hlsearch
set nowrap
set tabstop=4
set softtabstop=4
set expandtab
set shiftwidth=4
set showcmd
set clipboard=unnamed
set laststatus=2
set clipboard+=unnamedplus
set ru
