#set colors:
export LSCOLORS="ExGxFxdaCxDaDaxbadacac"

#greeting script:
/Users/drake/scripts/OSXey -c

#tmux greeting:
tmuxpid="$(pgrep tmux)"
if [ "${tmuxpid}" ];
then
    #stuff if running:
    echo "tmux is running..."
    echo "to attach, use: 'tmux attach -t monitor-vinculum'"
else
    #stuff if not running:
    echo "tmux is not running..."
    echo "to start and attach, use: 'tmux attach -t monitor-vinculum'"
fi

#[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

source ~/.profile

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
    fi
fi

