#aliases
alias psgrep='ps -e | grep'
alias vpnstop='sudo systemctl stop openvpn@Miami.service'
alias vpnstart='sudo systemctl start openvpn@Miami.service'
alias vpnstatus='systemctl status openvpn@Miami.service'
alias vpnkill='sudo killall openvpn'
alias please='sudo $( history -p !!)'
alias fuck='sudo $( history -p !!)'
alias fucking='sudo'
