# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH="/home/drake/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="less-fishy"  #custom theme, based on fishy
#ZSH_THEME="agnoster"
#ZSH_THEME="dieter"
#ZSH_THEME="arrow"
#ZSH_THEME="avit"
#ZSH_THEME="awesomepanda"
#ZSH_THEME="bureau"
#ZSH_THEME="candy-kingdom"
#ZSH_THEME="candy"
#ZSH_THEME="clean"
#ZSH_THEME="cypher"
#ZSH_THEME="daveverwer"
#ZSH_THEME="dstufft"
#ZSH_THEME="emotty"
#ZSH_THEME="fishy"
#ZSH_THEME="example"
#ZSH_THEME="gozilla"
#ZSH_THEME="half-life"
#ZSH_THEME="imajes"
#ZSH_THEME="kardan"
#ZSH_THEME="lambda"
#ZSH_THEME="maran"
#ZSH_THEME="mh"
#ZSH_THEME="michelebologna"
#ZSH_THEME="mikeh"
#ZSH_THEME="miloshadzic"
#ZSH_THEME="minimal"
#ZSH_THEME="mira"
#ZSH_THEME="mrtazz"
#ZSH_THEME="murilasso"
#ZSH_THEME="muse"
#ZSH_THEME="nanotech"
#ZSH_THEME="nicoulaj"
#ZSH_THEME="philips"
#ZSH_THEME="pure"
#ZSH_THEME="rgm"
#ZSH_THEME="robbyrussell"
#ZSH_THEME="sammy"
#ZSH_THEME="simple"
#ZSH_THEME="sonicradish"
#ZSH_THEME="sorin"
#ZSH_THEME="sunaku"
#ZSH_THEME="superjarin"
#ZSH_THEME="terminalparty"
#ZSH_THEME="tjkirch_mod"
#ZSH_THEME="tjkirch"
#ZSH_THEME="tonotdo"
#ZSH_THEME="wedisagree"
#ZSH_THEME="xiong-chiamiov"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
 ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git sudo)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi
export EDITOR=nvim

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# aliases file:
if [ -f ~/.zsh_aliases ];
then
    source ~/.zsh_aliases
fi
