export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="less-fishy"  #custom theme, based on fishy
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(git sudo colored-man-pages history-substring-search python rsync tmux zsh-autosuggestions )

source $ZSH/oh-my-zsh.sh

export EDITOR=nvim

# aliases file:
if [ -f ~/.zsh_aliases ];
then
    source ~/.zsh_aliases
fi

# secrets file:
if [ -f ~/.zsh_secrets ];
then
    source ~/.zsh_secrets
fi

# Tmux:
export ZSH_TMUX_CONFIG="$HOME/.tmux.conf"
# export DISABLE_AUTO_TITLE='true'

#for fun:
neofetch


# For Ruby (esp. Jekyll)
export GEM_HOME="$HOME/gems"
export PATH="$HOME/gems/bin:$PATH"
export PATH="$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"
