export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="less-fishy"  #custom theme, based on fishy
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(git sudo colored-man-pages history-substring-search python rsync tmux tmuxinator zsh-autosuggestions )

source $ZSH/oh-my-zsh.sh

export EDITOR=nvim

# aliases file:
if [ -f ~/.zsh_aliases ];
then
    source ~/.zsh_aliases
fi

# secrets file:
if [ -f ~/.zsh_secrets ];
then
    source ~/.zsh_secrets
fi

dist=$(uname -s)
if [[ "${dist}" -eq "Linux" ]]
then
    #for fun:
    neofetch
fi
