#aliases:
alias psgrep='ps -e | grep'                                                                                                    
alias vpnkill='sudo killall openvpn'
alias please='sudo $( history -p !!)'
alias fuck='sudo $( history -p !!)'
alias fucking='sudo'
alias ll='ls -lhAp'
